spring.application.name=bff

# Puerto de la API
server.port=${SERVER_PORT:8084}

# Seguridad OAuth2 Resource Server (JWT de Azure Entra ID)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID:e34a6311-e69d-4a97-bedf-2ad7cc5455a0}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=46cda96c-1ab7-42af-a838-5ad46de31226

# URL de cada microservicio (default: API Gateway)
bff.microservicios.usuario.url=${MICROSERVICIOS_USUARIO_URL:https://diesx6267g.execute-api.us-east-1.amazonaws.com}
bff.microservicios.reserva.url=${MICROSERVICIOS_RESERVA_URL:https://diesx6267g.execute-api.us-east-1.amazonaws.com}
bff.microservicios.servicio.url=${MICROSERVICIOS_SERVICIO_URL:https://diesx6267g.execute-api.us-east-1.amazonaws.com}

# Espera maxima al responder un microservicio (ms)
bff.microservicios.timeout=${MICROSERVICIOS_TIMEOUT:4000}